### ISSUE TITLE
[Error] City couldn't found. Please enter the city name correctly.

### ISSUE THREAD

**Issue by osama2kabdullah** [smhabibjr/weather-app-using-OpenWeather-api#1]
I replace the API key in app/controllers/weather_controller.rb file. (Ln no. 11)

```ruby
api = "https://.....appid=#{api_code}&.....ric"
```
I replace `{api_code}` to `c55...........44584`

After that I follow the command that you mentioned. This app running on `localhost:3000` also.

![Screenshot (91)](https://user-images.githubusercontent.com/109265357/213253755-c97913d8-9d06-495c-bcb1-d52fd8562d78.png)

---

But after submit the Error happen

![Screenshot (92)](https://user-images.githubusercontent.com/109265357/213254311-70ac5c31-506c-49d0-b4ac-af26a7a40f89.png)

**Comment by smhabibjr** [comment]
First of all, I appreciate your issue. I also check again. but couldn't find any error to search Khulna. As you can see in the screenshot below.

![image](https://user-images.githubusercontent.com/77357735/215234327-c80ce579-aa3d-4e1d-8a04-2dad7aa10cc6.png)


What you can do ?

Step 1. Make sure you replace the api_code correctly. 

For example, your open weather API code is like this:  `6grt3434rf4564545f343434`

After replacing, API variable value would be like the below. (Ln no. 11)

` api = "https://api.openweathermap.org/data/2.5/weather?q=#{city_name}&appid=6grt3434rf4564545f343434&units=metric"
`

Step 2. Rebuild your docker image and run the docker container again. You can also delete the previous image and container for my-weather-app before rebuilding it again.

To rebuild your docker image. Open the terminal from your project directory.
````
docker build . -t my-weather-app
````
Build and Run the container.
````
docker run -p 3000:3000 my-weather-app
````
After running the container. Go to the browser and curl http://localhost:3000

Hope it'll work if not please let me know. It would be always appreciated.

**Comment by osama2kabdullah** [comment]
> First of all, I appreciate your issue. I also check again. but couldn't find any error to search Khulna. As you can see in the screenshot below.
> 
> ![image](https://user-images.githubusercontent.com/77357735/215234327-c80ce579-aa3d-4e1d-8a04-2dad7aa10cc6.png)
> 
> What you can do ?
> 
> Step 1. Make sure you replace the api_code correctly.
> 
> For example, your open weather API code is like this: `6grt3434rf4564545f343434`
> 
> After replacing, API variable value would be like the below. (Ln no. 11)
> 
> `api = "https://api.openweathermap.org/data/2.5/weather?q=#{city_name}&appid=6grt3434rf4564545f343434&units=metric"`
> 
> Step 2. Rebuild your docker image and run the docker container again. You can also delete the previous image and container for my-weather-app before rebuilding it again.
> 
> To rebuild your docker image. Open the terminal from your project directory.
> 
> ```
> docker build . -t my-weather-app
> ```
> 
> Build and Run the container.
> 
> ```
> docker run -p 3000:3000 my-weather-app
> ```
> 
> After running the container. Go to the browser and curl http://localhost:3000
> 
> Hope it'll work if not please let me know. It would be always appreciated.

Its working. Thanks

**Comment by smhabibjr** [comment]
I also add a country-wise city picker. You can pull the branch to update
your project.
